server:
   error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/scrib
    username: postgres
    password: mindig
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: com.services.util.hibernate.ModifiedImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation=true: true